add_executable(platform_uart_unit_tests UartTest.cpp)

target_include_directories(platform_uart_unit_tests PRIVATE ${CMAKE_SOURCE_DIR}/tests/mocks)

target_link_libraries(platform_uart_unit_tests PRIVATE platform_hal GTest::gtest_main)

target_compile_features(platform_uart_unit_tests PRIVATE cxx_std_17)

gtest_discover_tests(platform_uart_unit_tests)

add_executable(platform_async_uart_unit_tests AsyncUartTest.cpp)

target_include_directories(platform_async_uart_unit_tests PRIVATE ${CMAKE_SOURCE_DIR}/tests/mocks)

target_link_libraries(platform_async_uart_unit_tests PRIVATE platform_hal GTest::gtest_main)

target_compile_features(platform_async_uart_unit_tests PRIVATE cxx_std_17)

gtest_discover_tests(platform_async_uart_unit_tests)
